# Change these first
owner: mikepell007 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: BI
    url: $BI
    port: 80
    check: "tcp-ping"
  - name: EDI
    url: $EDI
    port: 80
    check: "tcp-ping"
  - name: Cams
    url: $CAMS_URL
    type: globalping
    location: north america
  - name: Files
    url: $FILES_URL
  - name: ForgeJo
    url: $FORGEJO_URL
  - name: FreshRSS
    url: $FRESHRSS_URL
  - name: Graylog
    url: $GRAYLOG_URL
  - name: HA
    url: $HA_URL
  - name: Naemon
    url: $NAEMON_URL
  - name: Nextcloud
    url: $NEXTCLOUD_URL
  - name: Notes
    url: $NOTES_URL
  - name: Remote
    url: $REMOTE_URL

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
